import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"; // Correct this line
import NavBar from "./components/NavBar/NavBar";
import { Toaster } from "react-hot-toast";

// Fix the variable name to be consistent
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Music List App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Toaster
          toastOptions={{
            style: { background: "rgb(51 65 85)", color: "#fff" },
            duration: 3000,
          }}
          position="top-center"
          reverseOrder={false}
        />
        <div>
          <NavBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
